version: '3.3'
services:
    test-react:
        container_name: wonder
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            TZ: 'Asia/Seoul'
