server:
  port: 8081

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/wonder
#    username: root
#    password: 1234
#    dirver-class-name: com.mysql.jdbc.Driver
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    generate-ddl: true
    database-platform: H2
    hibernate:
      ddl.auto: create
#    show_sql: true
    defer-datasource-initialization: true
    properties:
      default_batch_fetch_size: 1000

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

firebase:
  config-file: ./serviceAccountKey.json
  bucket: wonder-d0e26.appspot.com
  private-url: https://storage.googleapis.com/download/storage/v1
  public-url: https://firebasestorage.googleapis.com/v0

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace