server:
  port: 8081

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/wonder
#    username: root
#    password: 1234
#    dirver-class-name: com.mysql.jdbc.Driver
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    generate-ddl: true
    database-platform: H2
    show-sql: true
    hibernate:
      ddl.auto: create

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace